### ISSUE TITLE
This does not show up on the organization page.

### ISSUE THREAD

**Issue by pradhan-ritik** [Thornton-Middle-School/.github#1]
This is what it looks like signed out. 
It's still not there even if you are a member.
![image](https://github.com/user-attachments/assets/a62ec482-031f-4869-8c06-b020007d3899)
I'm assuming the whole point of this repository is for it to show up on the organization page. If it's not I will close this issue.

**Comment by Pramad712** [comment]
Yeah it is lol

**Comment by pradhan-ritik** [comment]
Huh, for some reason I didn't see it yesterday.

**Comment by Pramad712** [comment]
i meant it is as in it was not there lol. I added the link like 30 mins ago.

**Comment by pradhan-ritik** [comment]
yea ik
